export const DICT_TYPE = {
  bool: "bool",
  roleStatus: "role_status",
  userStatus: "user_status",
  messageType: "message_type",
  datasourceType: "datasource_type",
  sqlStatus: "sql_status",
  fileEncoding: "file_encoding",
  taskStatus: "task_status",
};

export const PRIVILEGES = {
  roleSuperAdmin: '_super_admin',
  sysDicDctShow: 'sys:dic:dct:0',
  wsWssWpiEdit: 'ws:wss:wpi:2',
  dstDftDftShow: 'dst:dft:dft:0',
  wsWshDftShow: 'ws:wsh:dft:0',
  wsDftDftShow: 'ws:dft:dft:0',
  sysRolRliShow: 'sys:rol:rli:0',
  sysRolRliGrant: 'sys:rol:rli:4',
  wsWssWpiAdd: 'ws:wss:wpi:1',
  sysUsrUliEdit: 'sys:usr:uli:2',
  sysUsrUliDelete: 'sys:usr:uli:3',
  sysDicDcdAdd: 'sys:dic:dcd:1',
  sysDicDcdDelete: 'sys:dic:dcd:3',
  dgDgdDdiShow: 'dg:dgd:ddi:0',
  wsWsdWdlEdit: 'ws:wsd:wdl:2',
  wsWseDftShow: 'ws:wse:dft:0',
  sysUsrDftShow: 'sys:usr:dft:0',
  sysDicDctAdd: 'sys:dic:dct:1',
  wsWsdDftShow: 'ws:wsd:dft:0',
  sysRolRliAdd: 'sys:rol:rli:1',
  wsWssWpiDelete: 'ws:wss:wpi:3',
  dgDgmDftShow: 'dg:dgm:dft:0',
  sysUsrUliAdd: 'sys:usr:uli:1',
  dgDgdDdiEdit: 'dg:dgd:ddi:2',
  sysUsrUliShow: 'sys:usr:uli:0',
  sysDicDcdShow: 'sys:dic:dcd:0',
  sysDftDftShow: 'sys:dft:dft:0',
  dgDgmDmiShow: 'dg:dgm:dmi:0',
  dgDgeDeiShow: 'dg:dge:dei:0',
  wsWssWpiShow: 'ws:wss:wpi:0',
  dgDgmDmiDelete: 'dg:dgm:dmi:3',
  wsWssDftShow: 'ws:wss:dft:0',
  sysDicDftShow: 'sys:dic:dft:0',
  wsWseWheShow: 'ws:wse:whe:0',
  dgDgmDmiAdd: 'dg:dgm:dmi:1',
  dgDgdDftShow: 'dg:dgd:dft:0',
  sysRolRliEdit: 'sys:rol:rli:2',
  dgDgsDgiShow: 'dg:dgs:dgi:0',
  dgDgdDdiDelete: 'dg:dgd:ddi:3',
  wsWsdWdlShow: 'ws:wsd:wdl:0',
  wsWsdWdlDelete: 'ws:wsd:wdl:3',
  wsWsoDftShow: 'ws:wso:dft:0',
  wsWsdWdlAdd: 'ws:wsd:wdl:1',
  dgDgeDftShow: 'dg:dge:dft:0',
  sysDicDctEdit: 'sys:dic:dct:2',
  dgDftDftShow: 'dg:dft:dft:0',
  dgDgeDeiAdd: 'dg:dge:dei:1',
  sysRolRliDelete: 'sys:rol:rli:3',
  dgDgsDgiDelete: 'dg:dgs:dgi:3',
  wsWshWhlShow: 'ws:wsh:whl:0',
  sysDicDcdEdit: 'sys:dic:dcd:2',
  dgDgsDgiEdit: 'dg:dgs:dgi:2',
  dgDgsDftShow: 'dg:dgs:dft:0',
  wsWsiWhiShow: 'ws:wsi:whi:0',
  dgDgmDmiEdit: 'dg:dgm:dmi:2',
  sysDicDctDelete: 'sys:dic:dct:3',
  sysSetDftShow: 'sys:set:dft:0',
  dgDgsDgiAdd: 'dg:dgs:dgi:1',
  wsWsiDftShow: 'ws:wsi:dft:0',
  dgDgeDeiDelete: 'dg:dge:dei:3',
  sysRolDftShow: 'sys:rol:dft:0',
  sysDicDctDetail: 'sys:dic:dct:7',
  dgDgdDdiAdd: 'dg:dgd:ddi:1',
  dgDgeDeiEdit: 'dg:dge:dei:2',
};

export const PATTERNS = {
  characterWord: /^[a-zA-Z0-9_]+$/,
  excludeSpecialChar:
    /^[^\s\\\.\[\]\{\}\(\)\<\>\*\+\-\=\!\?\^\$\|~、/,【】《》。·`：；“”"':;]+$/,
};

export const DB_STORES = {
  tableMeta: "tableMeta",
};
