name: DMS CI

on:
  push:
    branches: [ 'main','dev','feature/**','releases/**' ]
    paths-ignore: [ '**/*.md', '**/*.svg','**/*.png' ]
  pull_request:
    branches: [ 'main','dev','feature/**','releases/**' ]
    paths-ignore: [ '**/*.md', '**/*.svg','**/*.png' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Jdk Env ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'corretto'
          cache: 'maven'
      - name: Build Project With Maven
        run: mvn clean package -B -U -T 4 '-Dmaven.test.skip=true' --file pom.xml