name: DMS CI

on:
  push:
    branches: [ 'main','feature/**','releases/**' ]
    paths-ignore: [ '**/*.md', '**/*.svg','**/*.png' ]
  pull_request:
    branches: [ 'main','feature/**','releases/**' ]
    paths-ignore: [ '**/*.md', '**/*.svg','**/*.png' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 8,11,17 ]
      runs-on: ${{ matrix.os }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Setup jdk env ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'corretto'
          cache: 'maven'
      - name: Build project with maven
        run: mvn clean package -B -U -T 4 -Dmaven.test.skip=true --file pom.xml