name: Publish Docker Image

on:
  workflow_dispatch:

env:
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_REPO: basedt

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - service_name: "build-backend-amd64"
            image_name_env: "amd64"
            image: "dms-backend"
#            context: "api"
            platform: linux/amd64
          - service_name: "build-backend-arm64"
            image_name_env: "arm64"
            image: "dms-backend"
#            context: "api"
            platform: linux/arm64
          - service_name: "build-frontend-amd64"
            image_name_env: "amd64"
            image: "dms-frontend"
#            context: "web"
            platform: linux/amd64
          - service_name: "build-frontend-arm64"
            image_name_env: "arm64"
            image: "dms-frontend"
#            context: "web"
            platform: linux/arm64

#        platform: [ linux/amd64 , linux/arm64 ]
#        image: [ dms-backend , dms-frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
          cache: 'maven'
      - name: Build Project With Maven
        run: mvn clean package -B -U -T 4 '-Dmaven.test.skip=true' --file pom.xml
      - name: Extract project version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ matrix.image_name_env }}
#      - name: Login to Aliyun
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.ALIYUN_REGISTRY }}
#          username: ${{ secrets.DOCKER_REGISTRY_USER }}
#          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          file: scripts/docker/build/${{ matrix.image }}/Dockerfile
          context: .
#          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_REPO }}/${{ matrix.image }}:${{ env.PROJECT_VERSION }}-${{ matrix.image_name_env }}
          tags: ${{ matrix.image }}:${{ env.PROJECT_VERSION }}-${{ matrix.image_name_env }}
          push: true
