name: Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64 , linux/arm64 ]
        image: [ dms-backend , dms-frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
          cache: 'maven'
      - name: Build Project With Maven
        run: mvn clean package -B -U -T 4 '-Dmaven.test.skip=true' --file pom.xml
      - name: Extract project version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          platforms:
            - linux/amd64
            - linux/arm64
          file: scripts/docker/build/${{ matrix.image }}/Dockerfile
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: gleiyu/${{ matrix.image }}:${{ env.PROJECT_VERSION }}
          push: true
